name: Lint and build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [24.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Verify linting
        run: npm run lint

      - name: Create release
        run: npm run release

      - uses: actions/upload-artifact@v7
        with:
          path: dist/build.zip
          archive: true
